version: "3"

services:
  dotnet:
    build: ./GuideTestAPI
    container_name: obras-api
    ports:
      - "5000:5000"
    networks:
      - net
  angular:
    build: ./GuideTestSPA
    container_name: obras-spa
    ports:
      - "4200:4200"
    networks:
      - net
networks:
  net: